language:
    - java
jdk:
    - oraclejdk8
#asudo: required
cache:
    directories:
    - $HOME/.m2
    - node_modules
dist: trusty
before_install:
    #- openssl aes-256-cbc -K $encrypted_a08d1d0bac4b_key -iv $encrypted_a08d1d0bac4b_iv -in ks.tar.enc -out ks.tar -d
    #- openssl aes-256-cbc -K $encrypted_0bf0cf7d480d_key -iv $encrypted_0bf0cf7d480d_iv -in secrets.tar.enc -out secrets.tar -d
    - openssl aes-256-cbc -K $encrypted_0bf0cf7d480d_key -iv $encrypted_0bf0cf7d480d_iv -in secrets.tar.enc -out secrets.tar -d
    - chmod +x mvnw
    - chmod +x install.sh
    - chmod +x deploy.sh
    - chmod +x secrets.tar
    - tar xvf secrets.tar
    - chmod 600 id_rsa
    - chmod 600 id_rsa.pub
    - chmod 600 config
install: "./install.sh"
script: "./deploy.sh"
