language:
    - java
jdk:
    - oraclejdk8
#asudo: required
# blocklist
branches:
  except:
  - legacy
  - experimental
cache:
    directories:
        - $HOME/.m2
        - node_modules
dist: trusty
addons:
  ssh_known_hosts:
  - 45.77.160.68
before_install:
    - chmod +x mvnw
    - chmod +x ./scripts/install.sh
    - chmod +x ./scripts/before_deploy.sh
    - chmod +x ./scripts/deploy.sh
#install: true
install: ./mvnw clean package -Pprod -DskipTests=true
script:
   - chmod +x ./scripts/deploy.sh
before_deploy: ./scripts/before_deploy.sh
#before_deploy:
    #- openssl aes-256-cbc -K $encrypted_0bf0cf7d480d_key -iv $encrypted_0bf0cf7d480d_iv -in travis-env/secrets.tar.enc -out ./secrets.tar -d
    #- chmod +x secrets.tar
    #- tar xvf secrets.tar
    #- chmod 600 id_rsa
    #- chmod 600 id_rsa.pub
    #- chmod 600 config
deploy:
    # deploy develop to the staging environment
    - provider: script
      skip_cleanup: true
      script: "./scripts/deploy.sh"
      on:
        branch: develop
    # deploy master to production
    - provider: script
      skip_cleanup: true
      script: "./scripts/deploy.sh"
      on:
        branch: master
