language:
    - java
jdk:
    - oraclejdk8
#asudo: required
# blocklist
branches:
  except:
  - legacy
  - experimental
cache:
    directories:
        - $HOME/.m2
        - node_modules
dist: trusty
addons:
  ssh_known_hosts:
  - 45.77.160.68
before_install:
    - chmod +x mvnw
    - chmod +x scripts/install.sh
install: ./mvnw clean package -Pprod -DskipTests=true
script: true
before_deploy: scripts/before_deploy.sh
deploy:
    # deploy develop to the staging environment
    - provider: script
      script: scripts/deploy.sh staging
      on:
        branch: develop
    # deploy master to production
    - provider: script
      script: scripts/deploy.sh production
      on:
        branch: master
